import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import { Inter } from "next/font/google";
import { Header } from "@/components/shared/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jb = JetBrains_Mono({
  variable: "--font-jb",
  subsets: ["cyrillic"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jb.variable} font-my-jetbrains-mono antialiased`}>
        <Header />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
